name: Deploy BookStore-Backend (GitHub Repository Name)
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t chubbsbunns/first-hire-backend  .
      - name: Publish Image to docker hub
        run: docker push chubbsbunns/first-hire-backend:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Pull image from docker hub
        run: docker pull chubbsbunns/first-hire-backend:latest
      - name: Delete old container
        run: docker rm -f first-hire-backend:latest
      - name: Run Docker Container
        run: docker run -d -p 3001:3001 --name first-hire-backendlatest -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' first-hire-backendlatest 